---
serialize_function: "JSON.parse"
de_serialize_function: "JSON.generate"
import_string: "require 'json'"
assert_functions:
    - assert_dict
    - assert_list
    - assert_float
    - assert_str
    - assert_bool
    - assert_int
    - assert_none
