---
serialize_function: "Oj.load"
de_serialize_function: "Oj.dump"
import_string: "require 'oj'"
assert_functions:
    - assert_dict
    - assert_list
    - assert_float
    - assert_str
    - assert_bool
    - assert_int
    - assert_none
