---
serialize_function: "json.loads"
de_serialize_function: "json.dumps"
import_string: "import json"
assert_functions:
    - assert_dict
    - assert_list
    - assert_float
    - assert_str
    - assert_bool
    - assert_int
    - assert_none
