---
serialize_function: "rapidjson.loads"
de_serialize_function: "rapidjson.dumps"
import_string: "import rapidjson"
assert_functions:
    - assert_dict
    - assert_list
    - assert_float
    - assert_str
    - assert_bool
    - assert_int
    - assert_none
