---
serialize_function: "simplejson.loads"
de_serialize_function: "simplejson.dumps"
import_string: "import simplejson"
assert_functions:
    - assert_dict
    - assert_list
    - assert_float
    - assert_str
    - assert_bool
    - assert_int
    - assert_none
