---
serialize_function: "ujson.loads"
de_serialize_function: "ujson.dumps"
import_string: "import ujson"
assert_functions:
    - assert_dict
    - assert_list
    - assert_float
    - assert_str
    - assert_bool
    - assert_int
    - assert_none
