---
serialize_function: "json5.parse"
de_serialize_function: "json5.stringify"
import_string: "const json5 = require('json5')"
assert_functions:
    - assert_dict
    - assert_list
    - assert_float
    - assert_str
    - assert_bool
    - assert_int
    - assert_none
